### ISSUE TITLE
Integrate automatic typehinting

### ISSUE THREAD

**Issue by kaitj** [afids/afids-utils#12]
**Describe the feature you'd like to see**
Make use of the sphinx extension `autodoc_docstring_signature` (or whichever extension is relevant) to automatically pick up type hints and drop the repeated type hint that is manually written in the docstrings.

**Comment by kaitj** [comment]
I am at a bit of a loss for this one - open to any ideas here.

1. Type hinting is automatic for the inputs, **but**, it doesn't seem to like to link to the correct documentation when using something like `PathLike`. It only links if `os.PathLike` is used, though I would like to avoid importing all of `os` if only `PathLike` is used. Something similar is happening with `numpy`, but that is a bit more difficult to debug.
2. Return types (afaik) have to be explicitly stated in the docstring.

**Comment by tkkuehn** [comment]
Just so I'm totally clear on the issue here, is [`sphinx-autodoc-typing`](https://github.com/tox-dev/sphinx-autodoc-typehints) the extension you tried here?

**Comment by kaitj** [comment]
This is still using ``sphinx.ext.autodoc` - was trying to replicate the working mapping from snakebids

**Comment by kaitj** [comment]
This ended up getting fixed by updates to the doc requirements to get it working again in #14.
